#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
setopt IGNOREEOF
bindkey '^D' delete-char

alias ll='ls -ltrhG'
alias lsd='ls -ltrh $(find $PWD -type f )'
alias cp='nocorrect cp -ip'
alias du='du -khs'

alias emacs='emacs -nw'
alias em='emacs'

alias y=':'

autoload bashcompinit && bashcompinit
complete -C '${PYENV_ROOT}/shims/aws_completer' aws

export PATH=$PATH:${HOME}/.nodebrew/current/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
export JAVA_TOOLS_OPTIONS="-Dlog4j2.formatMsgNoLookups=true"
