# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
setopt IGNOREEOF
bindkey '^D' delete-char

alias ll='ls -ltrhG'
alias lsd='ls -ltrh $(find $PWD -type f )'
alias cp='nocorrect cp -ip'
alias du='du -khs'

alias emacs='emacs -nw'
alias em='emacs'

alias y=':'

autoload bashcompinit && bashcompinit
complete -C '${PYENV_ROOT}/shims/aws_completer' aws

export HISTFILE=$HOME/.zsh_history
export PATH=$PATH:${HOME}/.nodebrew/current/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
export JAVA_TOOLS_OPTIONS="-Dlog4j2.formatMsgNoLookups=true"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
